system_user_name: kustosz
system_user_home: /opt/kustosz

run_system_requirements_root: true

use_system_nodejs: false
nodejs_version: "16"
nvm_dir: "{{ system_user_home }}/.nvm"

use_system_python: false
python_path: "python3"
pyenv_version: "2.3.0"
pyenv_dir: "{{ system_user_home }}/.pyenv"
pyenv_python_version: "3.10.4"

# Private variables
shell_wrapper_script: "{{ system_user_home }}/.shell_wrapper"
python_wrapper_script: "{{ system_user_home }}/.python_wrapper"
required_system_services:
  - redis
  - nginx
