system_user_name: kustosz
system_user_home: /opt/kustosz
nodejs_version: "16"
nvm_dir: "{{ system_user_home }}/.nvm"
pyenv_version: "2.3.0"
pyenv_dir: "{{ system_user_home }}/.pyenv"
python_version: "3.10.4"

shell_wrapper_script: "{{ system_user_home }}/.shell_wrapper"
python_wrapper_script: "{{ system_user_home }}/.python_wrapper"
