system_user_name: kustosz
system_user_home: /opt/kustosz

configure_nginx_server: true
configure_system_services: true
venv_path: "{{ system_user_home }}/.venv"
kustosz_base_dir: "{{ system_user_home }}/web"

nginx_template_path: "nginx/site-kustosz"
kustosz_internal_port: "8000"
kustosz_nginx_listen: "80"
kustosz_nginx_server_name: "localhost"
kustosz_nginx_extra_config: ""
frontend_path: "{{ kustosz_base_dir }}/staticfiles"
run_certbot: false
certbot_extra_args: ""

systemd_dispatcher_path: /usr/local/bin/kustosz-service-dispatcher

# Private variables
shell_wrapper_script: "{{ system_user_home }}/.kustosz_shell_wrapper"
kustosz_system_services:
  - web
  - worker
  - clock
  - feedfetcher
