# first used in system_requirements
system_user_name: kustosz
system_user_home: /opt/kustosz
system_user_shell: /bin/bash

run_system_requirements_root: true

use_postgres: true

use_system_nodejs: false
nodejs_version: "16"
nvm_path: "{{ system_user_home }}/.nvm"

use_system_python: false
python_path: "python3"

pyenv_path: "{{ system_user_home }}/.pyenv"
pyenv_python_version: "3.10.4"

# first used in install
kustosz_frontend_version: "latest"
kustosz_backend_version: "latest"

venv_path: "{{ system_user_home }}/.venv"
force_install_backend: false
force_install_frontend: false

extra_python_packages: ""

kustosz_base_dir: "{{ system_user_home }}/web"
db_path: "{{ kustosz_base_dir }}/db"
settings_path: "{{ kustosz_base_dir }}/settings"
frontend_path: "{{ kustosz_base_dir }}/staticfiles"

kustosz_settings_allowed_hosts: []

settings_local_path: ""

# first used in system_setup
configure_nginx_server: true
configure_system_services: true

nginx_template_path: "nginx/site-kustosz"
kustosz_internal_port: "8000"
kustosz_nginx_listen: "80"
kustosz_nginx_server_name: "localhost"
kustosz_nginx_extra_config: ""
run_certbot: false
certbot_extra_args: ""

systemd_dispatcher_path: /usr/local/bin/kustosz-service-dispatcher

# first used in setup
opml_path: "{{ system_user_home }}/opml"
opml_local_path: ""

web_user_name: kustosz
web_user_password: ""


# Private variables not meant to be changed
environment_activation_script: "{{ system_user_home }}/.kustosz_activate"
shell_wrapper_script: "{{ system_user_home }}/.kustosz_shell_wrapper"
python_wrapper_script: "{{ system_user_home }}/.kustosz_python_wrapper"
get_version_script: "{{ system_user_home }}/.kustosz_get_version.py"
required_system_services:
  - redis
  - nginx
nvm_installer_path: "{{ system_user_home }}/.nvm_install.sh"
nvm_version: "0.39.1"
pyenv_version: "2.3.0"
secret_key_file: "{{ system_user_home }}/.kustosz_secret_key"
kustosz_system_services:
  - web
  - worker
  - clock
  - feedfetcher
kustosz_system_services_unit_path: /etc/systemd/system/kustosz@.service
