- name: "[Debian] Create Kustosz virtual host configuration"
  ansible.builtin.template:
    src: "{{ nginx_template_path }}"
    dest: /etc/nginx/sites-available/kustosz

- name: "[Debian] Enable Kustosz virtual host configuration"
  ansible.builtin.file:
    src: /etc/nginx/sites-available/kustosz
    dest: /etc/nginx/sites-enabled/kustosz
    state: link
  notify: "Restart NGINX"
