- name: "[Red Hat] Create Kustosz virtual host configuration"
  ansible.builtin.template:
    src: "{{ nginx_template_path }}"
    dest: /etc/nginx/conf.d/kustosz.conf
    mode: 0644
  notify: "Restart NGINX"
