- name: "Create Kustosz service dispatcher script"
  ansible.builtin.template:
    src: systemd/bin/kustosz-service-dispatcher
    dest: "{{ systemd_dispatcher_path }}"
    mode: 0755
  notify: "Restart Kustosz system services"

- name: "Create Kustosz service unit file"
  ansible.builtin.template:
    src: "systemd/system/kustosz@.service"
    dest: "{{ kustosz_system_services_unit_path }}"
    mode: 0644
  notify: "Restart Kustosz system services"

- name: "Enable Kustosz system services"
  ansible.builtin.systemd:
    name: "kustosz@{{ item }}.service"
    enabled: true
  loop: "{{ kustosz_system_services }}"
