- name: "Set requested frontend version variable"
  ansible.builtin.command: >
    {{ python_path }} {{ get_version_script }}
    --component web-ui --version {{ kustosz_frontend_version }}
  register: _get_version
  changed_when: false

- name: "Set internal frontend variables"
  ansible.builtin.set_fact:
    _frontend_timestamp_path: "{{ frontend_path }}/.version"
    _frontend_archive_path: "{{ frontend_path }}/kustosz.tar.xz"
    _frontend_real_version: "{{ _get_version.stdout | trim }}"

- name: "Check current frontend version"
  ansible.builtin.command: >
    grep -q "{{ _frontend_real_version }}" "{{ _frontend_timestamp_path }}"
  register: _frontend_version_check
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: "Install Kustosz frontend"
  when:
    force_install_frontend or _frontend_version_check.rc != 0

  block:

    - name: "Clean up old frontend installation"
      ansible.builtin.file:
        path: "{{ frontend_path }}"
        state: "{{ item }}"
        owner: "{{ system_user_name }}"
        group: "{{ system_user_name }}"
        mode: 0755
      loop:
        - absent
        - directory

    - name: "Download frontend files"
      ansible.builtin.get_url:
        url: "https://github.com/KustoszApp/web-ui/releases/download/{{ _frontend_real_version }}/kustosz.tar.xz"
        dest: "{{ _frontend_archive_path }}"

    - name: "Unpack frontend files"
      ansible.builtin.unarchive:
        remote_src: true
        src: "{{ _frontend_archive_path }}"
        dest: "{{ frontend_path }}"
        owner: "{{ system_user_name }}"
        group: "{{ system_user_name }}"

    - name: "Remove downloaded archive"
      ansible.builtin.file:
        path: "{{ _frontend_archive_path }}"
        state: absent

    - name: "Put timestamp for future role runs"
      ansible.builtin.copy:
        dest: "{{ _frontend_timestamp_path }}"
        content: |
          {{ _frontend_real_version }}
        owner: "{{ system_user_name }}"
        group: "{{ system_user_name }}"
