- name: "Become user"
  block:

    - name: "Create Python virtual environment"
      import_tasks: venv.yml

    # FIXME: shouldn't put in ~/.bashrc blindly
    # FIXME: last three variables don't belong here logically
    - name: "Ensure venv is loaded automatically"
      ansible.builtin.blockinfile:
        path: "{{ system_user_home }}/.bashrc"
        block: |
          export VIRTUAL_ENV="{{ venv_path }}"
          export PATH="$VIRTUAL_ENV/bin:$PATH"
          export ENV_FOR_DYNACONF="production"
          export DJANGO_SETTINGS_MODULE=kustosz.settings
          export KUSTOSZ_BASE_DIR="{{ kustosz_base_dir }}"
        marker: "# {mark} Kustosz venv setup managed by Ansible"

    # FIXME: we shouldn't need to update installer every time new version is released
    #        there should be a tool that can grab latest versions for us automatically
    - name: "Install Kustosz backend server"
      import_tasks: backend.yml

    - name: "Install Kustosz node-readability script"
      import_tasks: node_readability.yml

    - name: "Create directories"
      ansible.builtin.file:
        path: "{{ item }}"
        state: "directory"
        owner: "{{ system_user_name }}"
        group: "{{ system_user_name }}"
        mode: 0755
      loop:
        - "{{ db_path }}"
        - "{{ settings_path }}"
        - "{{ frontend_path }}"

    - name: "Install frontend files"
      import_tasks: frontend.yml

    - name: "Copy settings files"
      import_tasks: settings.yml

  become: true
  become_user: "{{ system_user_name }}"
