- name: Check if Kustosz SECRET_KEY file exists
  ansible.builtin.stat:
    path: "{{ secret_key_file }}"
  register: _secret_key_file

- name: Create SECRET_KEY file
  when:
    - not _secret_key_file.stat.exists
  block:

    - name: Generate new secret key
      ansible.builtin.shell: "kustosz-manager generate_secret_key"
      args:
        executable: "{{ shell_wrapper_script }}"
      register: _generate_secret_key_result
      changed_when: false

    - name: Create SECRET_KEY file
      ansible.builtin.copy:
        dest: "{{ secret_key_file }}"
        content: |
          export DYNACONF_SECRET_KEY="{{ _generate_secret_key_result.stdout | trim }}"
        owner: "{{ system_user_name }}"
        group: "{{ system_user_name }}"
        mode: 0600
